# Generated by Django 6.1.1 on 2026-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
    ]
