# Generated by Django 6.1.1 on 2026-09-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
